name: Markdown URLs

on: [push, pull_request]

jobs:
  markdown-link-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes
          use-verbose-mode: yes
          config-file: docs/.markdown-link-check.json
          folder-path: docs/
          check-modified-files-only: yes
        