on: [push, pull_request]

name: MarkdownLint

jobs:
  MarkdownLint:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: markdownlint-cli (special files)
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: docs/hpc/software/software-repositories.md
          config_file: docs/hpc/software/.markdownlint.software-repositories.json

      - name: Remove special files
        run: rm docs/hpc/software/software-repositories.md
  
      - name: markdownlint-cli (remaining files)
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: docs/.markdownlint.json
