on: [push, pull_request]

name: Odds and Ends

jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    name: Odds and Ends
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4

    - name: usernames
      run: |
        make check-usernames

    - name: here-links
      run: |
        make check-here-links

    - name: absolute-links
      run: |
        make check-absolute-links

    - name: legacy
      run: |
        make check-legacy

