on: [push, pull_request]

name: 'TSV check'

jobs:
  spelling:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: 'latest' }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Check TSV files
        run: |
          make tsv-check
